export const plans = [
  {
    name: 'Founding Member',
    price: '49',
    description: 'Lock in the Founding Rate for life. Everything you need to turn one-time visitors into regulars.',
    popular: false,
    features: [
      'Custom customer opt-in page',
      'Branded QR code signs',
      'Automated Thank-You emails',
      'Review Request emails',
      'Comeback Offer emails',
      'Basic analytics dashboard',
      'Birthday Club rewards',
      'Referral request system',
      'Win-back campaigns',
      'Monthly campaign suggestions',
      'Customer tagging & segmentation',
      'Downloadable customer list',
      'Lifetime Rate Lock-in at $49/mo',
    ],
  },
  {
    name: 'Growth',
    price: '99',
    description: 'Accelerate your growth and build a community.',
    popular: true,
    features: [
      'Everything in Founding Member',
      'SMS/Text message marketing',
      'Advanced campaign builder',
      'Automated seasonal promotions',
      'AI-powered review reply suggestions',
      'Testimonial repurposing',
      'Priority support',
    ],
  },
  {
    name: 'Pro',
    price: '199',
    description: 'Maximum impact with advanced automation.',
    features: [
      'Everything in Growth',
      'Dedicated account manager',
      'Custom onboarding & training',
    ],
  },
];
