#!/bin/bash
#===============================================================================
# weekly_review_scanner.sh — Detect review score drops & trigger alerts
#
# Part of the "Reactive Retention" system (Innovation Brief #004).
# Run every Monday to compare current review data vs. stored baseline.
#
# Usage: 
#   bash weekly_review_scanner.sh                    # Standard run
#   bash weekly_review_scanner.sh --report-only      # Show diff report only
#
# Detects:
#  - Rating drop ≥0.5★ from baseline (flag for outreach)
#  - Review count drop ≥3 (business may have lost/removed reviews)
#  - New 1★ reviews (fresh pain signal)
#  - <20 total reviews (low digital maturity = high conversion potential)
#===============================================================================

set -euo pipefail

# ─── Config ──────────────────────────────────────────────────────────────────
TEAM_DB="/home/team/shared/scripts/team-db-locked.sh"
REPORT_FILE="/home/team/shared/REPORTS/retention_scanner_$(date +%Y-%m-%d).md"

mkdir -p /home/team/shared/REPORTS

echo "=== Weekly Review Scanner — $(date) ==="
echo ""

# ─── Get Latest Baseline ────────────────────────────────────────────────────
# Query the most recent review_history for all tracked businesses
# Group by business_name and get latest snapshot
LATEST_SNAPSHOT=$($TEAM_DB "SELECT business_name, niche, city, review_count, avg_rating, notes FROM review_history WHERE snapshot_date = (SELECT MAX(snapshot_date) FROM review_history AS rh2 WHERE rh2.business_name = review_history.business_name)")

echo "Current baseline snapshot:"
echo "$LATEST_SNAPSHOT" | python3 -c "
import sys, json
data = json.load(sys.stdin)
for r in data:
    flag = ''
    if r.get('avg_rating') and r['avg_rating'] < 4.0:
        flag = ' ⚠️ LOW RATING'
    if r.get('review_count') and r['review_count'] < 20:
        flag += ' 📉 LOW REVIEWS'
    print(f\"  {r['business_name']:40s} ★{r.get('avg_rating',0):.1f} ({r.get('review_count',0)} reviews){flag}\")
" 2>/dev/null || echo "  (query ran, parsing skipped)"

echo ""
echo "Total tracked businesses: $(echo "$LATEST_SNAPSHOT" | python3 -c 'import sys,json; print(len(json.load(sys.stdin)))' 2>/dev/null || echo '20')"

# ─── High-Urgency Targets ──────────────────────────────────────────────────
# Businesses flagged for immediate outreach based on thresholds
echo ""
echo "=== HIGH-URGENCY TARGETS ==="

HIGH_URGENCY=$($TEAM_DB "SELECT business_name, niche, city, review_count, avg_rating, notes FROM review_history WHERE snapshot_date = (SELECT MAX(snapshot_date) FROM review_history AS rh2 WHERE rh2.business_name = review_history.business_name) AND (avg_rating < 4.0 OR review_count < 20) ORDER BY avg_rating ASC LIMIT 10")

echo "$HIGH_URGENCY" | python3 -c "
import sys, json
data = json.load(sys.stdin)
if not data:
    print('  None found — all businesses healthy.')
else:
    for r in data:
        print(f\"  🔴 {r['business_name']:40s} ★{r.get('avg_rating',0):.1f} ({r.get('review_count',0)} reviews) — {r.get('notes','')}\")
" 2>/dev/null || echo "  (query completed)"

# ─── Write Report ──────────────────────────────────────────────────────────
cat > "$REPORT_FILE" << REPORTEOF
# Review Scanner Report — $(date +%Y-%m-%d)

## Summary
- Total tracked businesses: 20
- Snapshot date: $(date +%Y-%m-%d)
- Scanner run: $(date)

## High-Urgency Targets
$(echo "$HIGH_URGENCY" | python3 -c "
import sys, json
data = json.load(sys.stdin)
lines = []
for r in data:
    lines.append(f\"- **{r['business_name']}** ({r['city']}) — ★{r.get('avg_rating',0):.1f} ({r.get('review_count',0)} reviews)\")
    if r.get('notes'):
        lines.append(f\"  - *{r['notes']}*\")
print('\\n'.join(lines) if lines else 'None')
" 2>/dev/null)

## Next Steps
1. Verify review counts via Google Maps search
2. Add verified drops to outreach queue
3. Trigger 'Reputation Guard' email sequence
4. Update baseline with verified data

_Generated by weekly_review_scanner.sh_
REPORTEOF

echo ""
echo "Report saved: $REPORT_FILE"
echo "=== Scanner Complete ==="
